# Use the official Golang image
FROM golang:1.23-alpine AS base
WORKDIR /opt/kelhani/api/build

# Update system dependencies
RUN apk update && \
    apk upgrade && \
    go env -w CGO_ENABLED=0

# Install development dependencies
FROM base AS dev-deps
RUN go install github.com/air-verse/air@latest

# Development runner stage
FROM dev-deps AS dev-runner
WORKDIR /opt/kelhani/api/src
ENV GIN_MODE=debug
ENV PORT=8000
ENTRYPOINT ["air", "-c", ".air.toml"]

# Install project dependencies
FROM base AS deps
COPY go.mod go.sum ./
RUN go mod tidy && \
    go mod verify && \
    go mod download

# Production builder stage
FROM deps AS builder
COPY . .
RUN go build -o /opt/kelhani/api && \
    rm -r /opt/kelhani/api/build

# Production Runner stage
FROM builder AS runner
ENTRYPOINT ["/opt/kelhani/api"]